"""empty message

Revision ID: 5ad436a842bb
Revises: f1402cb54d05
Create Date: 2022-04-01 17:14:51.400725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad436a842bb'
down_revision = 'f1402cb54d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
